# Generated by Django 5.2.4 on 2025-07-31 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear_is_current'),
        ('accounts', '0002_remove_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
    ]
